from datetime import datetime
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, StringConstraints, field_validator

from app.models.matches import MatchProfileCard

MESSAGE_MAX = 2000


class MessageCreateRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    body: Annotated[str, StringConstraints(max_length=MESSAGE_MAX)]
    # Generated by the browser so a retried send is stored once.
    client_ref: UUID | None = None

    @field_validator("body")
    @classmethod
    def not_blank(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("Write a message before sending")
        return stripped


class MessageItem(BaseModel):
    id: UUID
    # The sender's profile id (PRD shape); sender_is_me saves clients from knowing their own id.
    sender_id: UUID
    body: str
    created_at: datetime
    sender_is_me: bool
    read_at: datetime | None
    client_ref: UUID | None


class MessageCreatedResponse(BaseModel):
    message_id: UUID
    message: MessageItem


class ThreadLastMessage(BaseModel):
    body: str
    created_at: datetime
    sender_is_me: bool


class ThreadItem(BaseModel):
    match_id: UUID
    partner: MatchProfileCard
    fit_score: float
    # False once the pair is no longer a mutual match: history stays readable (S6 edge case).
    can_send: bool
    unread_count: int
    last_message: ThreadLastMessage | None
    last_activity_at: datetime


class ThreadsResponse(BaseModel):
    items: list[ThreadItem]
    unread_total: int


class MessagesReadResponse(BaseModel):
    marked: int
    unread_total: int
