-- S6: one text thread per founder <-> investor/mentor pair. Writable while the pair is a mutual
-- match; earlier history stays readable if the connection ends.
create table public.messages (
  id uuid primary key default gen_random_uuid(),
  founder_profile_id uuid not null references public.profiles (id) on delete cascade,
  partner_profile_id uuid not null references public.profiles (id) on delete cascade,
  sender_profile_id uuid not null references public.profiles (id) on delete cascade,
  recipient_profile_id uuid not null references public.profiles (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  -- Generated by the browser so a retried send is stored once.
  client_ref uuid,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  check (founder_profile_id <> partner_profile_id),
  check (sender_profile_id in (founder_profile_id, partner_profile_id)),
  check (recipient_profile_id in (founder_profile_id, partner_profile_id)),
  check (sender_profile_id <> recipient_profile_id),
  unique (sender_profile_id, client_ref)
);

create index messages_thread_idx
  on public.messages (founder_profile_id, partner_profile_id, created_at desc);
create index messages_partner_idx on public.messages (partner_profile_id);
create index messages_recipient_unread_idx
  on public.messages (recipient_profile_id) where read_at is null;
create index messages_recipient_idx on public.messages (recipient_profile_id);
create index messages_created_at_idx on public.messages (created_at);

alter table public.messages enable row level security;
revoke all on public.messages from anon;

create policy "messages read own"
on public.messages for select to authenticated
using (
  sender_profile_id in (
    select id from public.profiles where user_id = (select private.current_user_id())
  )
  or recipient_profile_id in (
    select id from public.profiles where user_id = (select private.current_user_id())
  )
);

alter table public.notifications
  drop constraint notifications_kind_check,
  add constraint notifications_kind_check check (
    kind in (
      'new_match', 'new_matches', 'intro_received', 'mutual_match', 'match_interest',
      'matching_paused', 'intro_cancelled',
      'meeting_booked', 'meeting_reminder', 'meeting_invite', 'scheduling_link_request',
      'meeting_outcome_prompt', 'message_received'
    )
  );
